### ISSUE TITLE
[Feature Request]: more reliable bus for accessories

### ISSUE THREAD

**Issue by prchal** [DCC-EX/EX-IOExpander#46]
### Problem/idea statement

I don't know how reliable I2C bus is on bigger layouts, but I'm afraid not perfect. What about using UART TTL or even better RS485.

**Comment by peteGSX** [comment]
There are a number of options available to increase I2C range, and these are all hardware options. Sparkfun/Adafruit have extenders available, and there are also DIY options available I believe.

Nothing within the EX-IOExpander software itself can enable that though, so closing this one off.
