### ISSUE TITLE
Bug Report: Variable not declard

### ISSUE THREAD

**Issue by martinfantini** [DCC-EX/EX-IOExpander#51]
### Version

HEAD

### Bug description

The variable is not declared as [bool](https://github.com/DCC-EX/EX-IOExpander/blob/main/EX-IOExpander.ino#L81) :

```
#ifdef DIAG
  diag = true;
#else
  bool diag = false;
#endif
```

The solution is:

```
#ifdef DIAG
  bool diag = true;
#else
  bool diag = false;
#endif
```

### Steps to reproduce the bug

Not compile if you enable the `DIAG` compilation variable.

### Expected behaviour

Compile. 

### Hardware in use

EX-IOExpander Arduino Mega

**Comment by peteGSX** [comment]
Will fix this along with https://github.com/DCC-EX/EX-IOExpander/issues/49

**Comment by martinfantini** [comment]
Nice. Thanks! I will glad to do the code review.
